name: Release quilt_rs

on: workflow_dispatch

env:
  PACKAGE_VERSION: ""
  PUBLISHED_VERSION: ""

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        package:
          - name: quilt-rs
            registryName: quilt-rs
            path: quilt-rs
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rust for release
        uses: ./.github/actions/setup-rust-minimal
        with:
          cache-target: release

      - name: Get Version
        working-directory: ${{ matrix.package.path }}
        run: echo PACKAGE_VERSION=$(sed -nE 's/^\s*version = "(.*?)"/\1/p' Cargo.toml) >> $GITHUB_ENV

      - name: Check Published Version
        run: echo PUBLISHED_VERSION=$(cargo search ${{ matrix.package.registryName }} --limit 1 | sed -nE 's/^[^"]*"//; s/".*//1p' -) >> $GITHUB_ENV

      - name: Authenticate with crates.io via OIDC
        if: env.PACKAGE_VERSION != env.PUBLISHED_VERSION
        uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Cargo Package
        if: env.PACKAGE_VERSION != env.PUBLISHED_VERSION
        working-directory: ${{ matrix.package.path }}
        run: |
          cargo package
          echo "We will publish:" $PACKAGE_VERSION
          echo "This is current latest:" $PUBLISHED_VERSION

      - name: Publish ${{ matrix.package.name }}
        if: env.PACKAGE_VERSION != env.PUBLISHED_VERSION
        working-directory: ${{ matrix.package.path }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          echo "# Cargo Publish"
          cargo publish --no-verify
