name: Release QuiltSync

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true

jobs:
  build:
    uses: ./.github/workflows/build-quilt-sync.yaml
    with:
      platforms: |
        {
          "include": [
            {"platform": "macos-15", "args": "--target aarch64-apple-darwin"},
            {"platform": "macos-15", "args": "--target x86_64-apple-darwin"},
            {"platform": "ubuntu-22.04", "args": ""},
            {"platform": "windows-latest", "args": ""}
          ]
        }
      environment: ${{ inputs.environment }}
      prerelease: false
    secrets: inherit
