on: [push]

name: build

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: stable
            components: rustfmt, clippy
      - name: Check formatting
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy -- --deny warnings
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: debug
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
