name: Test quilt_rs

on:
  push:
    paths:
      - "quilt-rs/**"
      - "quilt-cli/**"
      - "Cargo.*"
      - "rust-toolchain.toml"
      - ".github/workflows/test-quilt-rs.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust for development
        uses: ./.github/actions/setup-rust-dev

      - name: Check formatting
        run: cargo fmt --check -p quilt-rs -p quilt-cli

      - name: Lint
        run: cargo clippy -p quilt-rs -p quilt-cli -- --deny warnings

      - name: Test library
        run: cargo test -p quilt-rs --verbose
        env:
          RUST_BACKTRACE: 1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Test CLI
        run: cargo test -p quilt-cli --verbose
        env:
          RUST_BACKTRACE: 1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build library
        run: cargo build -p quilt-rs --verbose

      - name: Build CLI
        run: cargo build -p quilt-cli --verbose
